[package]
name = "spot-checker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
fantoccini = "0.19.3"
image = "0.24.7"
tokio = { version = "1.34.0", features = ["full"] }
